version: '3'

services:
  app:
    image: python:3.10.12-slim-bullseye
    build:
      context: .
    working_dir: /app
    volumes:
      - .:/app
    environment:
      PATH: "/app/venv/bin:$PATH"
    command: >
      bash -c "
      apt-get update && \
      apt-get install -y --no-install-recommends build-essential libffi-dev cmake libcurl4-openssl-dev nodejs screen && \
      python -m pip install --no-cache-dir -U pip==23.2.1 && \
      python3 -m venv venv && \
      pip install --no-cache-dir -r requirements.txt && \
      chmod +x ./app.py && \
      chmod -R 777 /app && \
      screen -d -m python3 check.py && \
      uvicorn app:app --host 0.0.0.0 --port 7860
      "
    ports:
      - "7860:7860"
